USE ROLE TRAINING_ROLE;
USE WAREHOUSE BLUEJAY;
USE DATABASE USER_DB_BLUEJAY;
USE SCHEMA RAW;

-- creating forcast model 
CREATE OR REPLACE VIEW RAW.V_WEATHER_TRAIN AS
SELECT
  TO_VARIANT(LOCATION_NAME) AS SERIES,
  TO_TIMESTAMP_NTZ(DATE) AS TS,
  TEMP_MEAN::FLOAT AS Y
FROM RAW.WEATHER_DATA
WHERE TEMP_MEAN IS NOT NULL;

-- built in snowflake model used 
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST RAW.WEATHER_TEMP_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'RAW.V_WEATHER_TRAIN'),
  SERIES_COLNAME =>'SERIES',
  TIMESTAMP_COLNAME =>'TS',
  TARGET_COLNAME =>'Y'
);

-- tabel creation 
CREATE TABLE IF NOT EXISTS RAW.WEATHER_FORECAST (
  SERIES VARIANT,
  TS TIMESTAMP_NTZ,
  FORECAST FLOAT,
  LOWER_BOUND FLOAT,
  UPPER_BOUND FLOAT
);

DELETE FROM RAW.WEATHER_FORECAST;
-- 7 day output 
INSERT INTO RAW.WEATHER_FORECAST (SERIES, TS,FORECAST,LOWER_BOUND, UPPER_BOUND)
SELECT SERIES, TS,FORECAST,LOWER_BOUND,UPPER_BOUND
FROM TABLE(
  RAW.WEATHER_TEMP_MODEL!FORECAST(FORECASTING_PERIODS => 7)
);

-- union of forcast and actual data 

CREATE OR REPLACE TABLE RAW.WEATHER_FINAL AS
SELECT
  LOCATION_NAME,
  DATE AS DS,
  TEMP_MAX::FLOAT AS ACTUAL,
  NULL::FLOAT AS FORECAST,
  NULL::FLOAT AS LOWER_BOUND,
  NULL::FLOAT AS UPPER_BOUND
FROM RAW.WEATHER_DATA
UNION ALL
SELECT
  SERIES::STRING AS LOCATION_NAME,
  TO_DATE(TS) AS DS,
  NULL::FLOAT AS ACTUAL,
  FORECAST::FLOAT AS FORECAST,
  LOWER_BOUND::FLOAT AS LOWER_BOUND,
  UPPER_BOUND::FLOAT AS UPPER_BOUND
FROM RAW.WEATHER_FORECAST;

-- verifying everything 
SELECT 'WEATHER_FORECAST' AS table_name, COUNT(*) AS row_count FROM RAW.WEATHER_FORECAST;
SELECT
  'WEATHER_FINAL' AS table_name,
  COUNT(*) AS total_rows,
  COUNT(ACTUAL) AS actual_rows,
  COUNT(FORECAST) AS forecast_rows
FROM RAW.WEATHER_FINAL;
